### ISSUE TITLE
parallax.js is loaded before its dependencies

### ISSUE THREAD

**Issue by arowla** [CommerceDataService/DataService_WebSite#46]
See console for err on missing ref to '$'

**Comment by arowla** [comment]
Parallax script import and other JS should probably be moved to the bottom of the page (I think(?) that is convention)

**Comment by maabrown** [comment]
So I moved the script to the bottom of the page (and added a script tag to bring in JQuery) and it caused a conflict with DoC's jQuery (it said that jQuery('accordion-menu') wasn't a function - line 895). I then deleted the file and the parallax still works but I don't know why.

**Comment by arowla** [comment]
Merged #51
