### ISSUE TITLE
Change "Apply" pane

### ISSUE THREAD

**Issue by tyronegrandison** [CommerceDataService/DataService_WebSite#5]
Change it to "Contact Us"

**Comment by tyronegrandison** [comment]
@radhikabhatt26 @dcwebmaven We are moving away from active hiring.

**Comment by radhikabhatt26** [comment]
Suggestions:
- need content: name(s) and number(s) of people to contact. 
- display of DOC department logos could be better
  - make all the logos the same size/shape. Right now some of rectangular/some of circles, we could fit all of them into circles and some space between each logo
- make CDS logo larger and more prominent
  @tyronegrandison @dcwebmaven

**Comment by tyronegrandison** [comment]
The names and numbers should be of the CDS team members. 

Great ideas on logos.
