### ISSUE TITLE
Replaced Services section with images and text for new focus

### ISSUE THREAD

**Issue by tyronegrandison** [CommerceDataService/DataService_WebSite#50]
Services section should say we do:
1. Data Products & Services
    - Development, delivery and consulting on Open Data and API projects; involving integration, analysis, visualization and increased utilization. 
2. Data Science
    - Transforming raw data into insights, products, and applications to empower data-driven decision making.
3. Data Education
    - Providing employees with data science skills for the information age. 

We need an image for each function.

@radhikabhatt26 @maabrown

**Comment by radhikabhatt26** [comment]
@tyronegrandison  Should the 3 categories be development, data science, and education? I'm planning on making icons for each category.

**Comment by tyronegrandison** [comment]
@radhikabhatt26 yes, that is correct.
