### ISSUE TITLE
Increase text in the "Contact Us" section

### ISSUE THREAD

**Issue by tyronegrandison** [CommerceDataService/DataService_WebSite#83]

**Comment by radhikabhatt26** [comment]
@tyronegrandison What text should be "increased" in this section?

**Comment by tyronegrandison** [comment]
"The Commerce Data Service collaborates with the 12 Bureaus of the U.S. Department of Commerce
and private sector partners to improve data product delivery from science to society.
To contact us, please send an email to:" @radhikabhatt26
